### ISSUE TITLE
WG5 UseCase ERA5Land and xesmf error 

### ISSUE THREAD

**Issue by Cri-dei** [bopen/c3s-eqc-toolbox-template#19] opened 2023-02-28 13:26 UTC
Hi @malmans2,

I am Cristina Deidda I am part of WG5 and developing a Use Case code for Era5Land. I managed to enter in the Virtual Machine and install the packages.

If I just run:

import warnings
import xarray as xr
from c3s_eqc_automatic_quality_control import diagnostics, download
warnings.filterwarnings("ignore")

I have this error: ModuleNotFoundError: No module named 'xesmf'

I tried to install it but seems there are dependency issue with the package esmpy.
 
![image](https://user-images.githubusercontent.com/56677048/221866581-44f47851-37cd-4baf-84ba-32eb9666c2f0.png)

Can I have help for solving this issue?
Moreover, I started writing the code for a UseCase for Thier3b. I attached here the Jupiter notebook script. I would like to have some feedback about the code, if in this way can be okay for the WG5 delivery.

[Usecase_Summer Temperature trend in East Europe_v1.zip](https://github.com/bopen/c3s-eqc-toolbox-template/files/10850697/Usecase_Summer.Temperature.trend.in.East.Europe_v1.zip)

It still a draft version but I would like to know if I am going in the right direction.

Thank you,
Cristina

**Comment by malmans2** [comment] 2023-02-28 13:39
Hi @Cri-dei ,

> I tried to install it but seems there are dependency issue with the package esmpy.

I think you installed an old environment. The instructions to install the latest environment are in the README of this repo.
I suggest to re-create your environment from scratch. Could you please try this:
```
git clone https://github.com/bopen/c3s-eqc-toolbox-template.git
cd c3s-eqc-toolbox-template
conda create -n deidda -c conda-forge python=3.10 ipython
conda activate deidda
make template-update
```
Let me know if that works OK.

> I would like to have some feedback about the code, if in this way can be okay for the WG5 delivery.

I'll take a look in the next couple of days!

**Comment by Cri-dei** [comment] 2023-02-28 13:41
@malmans2 thank you!

**Comment by malmans2** [comment] 2023-02-28 13:43
FYI: I edited my previous comment because I copy-pasted the wrong command.
The last command to update the environment is: `make conda-env-update`

**Comment by malmans2** [comment] 2023-02-28 16:51
Hi @Cri-dei,
Looks like you don't make use of `c3s_eqc_automatic_quality_control`, and you are analysing data that has been previously downloaded.

To begin with, instead of loading pre-existing files, you should use `c3s_eqc_automatic_quality_control.download` on top of your notebook. You'll see that the software that we are developing caches all downloaded files.

All the [template notebooks](https://github.com/bopen/c3s-eqc-toolbox-template/tree/main/notebooks) make use of `download.download_and_transform`, so you should be able to figure out how to do the same for your dataset. You can also check the documentation with `help(download.download_and_transform)`. But if you have any question, feel free to ask.

**Comment by Cri-dei** [comment] 2023-03-01 08:44
Hi @malmans2 ,
Yes I know it, it is also written it in the first comment of the code. I did not put that line of command since I had the bug that I reported here and I can not directly download the data. So the definitive code will have that part at the start to automatically download the data.
I would like to know the feedback in general on the structure of the code if can be okay for the UseCase delivery.

**Comment by malmans2** [comment] 2023-03-01 10:20
Got it. Once you revise the code using data directly downloaded from the cds, I can help improving it. It's already in good shape to me, we can probably just make use of other diagnostics and plotting functions we already implemented. We can also add new diagnostics specific for your case, and we will check whether the code works ok with large datasets.

I can't really comment on the content as we are just providing technical support. If you haven't done it yet, you should check with Chunxue whether the output is il line with the UseCase delivery.

**Comment by Cri-dei** [comment] 2023-03-07 10:27
Hi @malmans2 ,

Thanks for the work that you and Vincenzo did, I am now able to run Jupyter and the main packages without error. 
I was just do some trials with a code that you provide in the Notebook. I can do and run the request with no errors. 
Once I compute:
ds_mean = download.download_and_transform(
    collection_id,
    requests,
    transform_func=diagnostics.spatial_weighted_mean,
    chunks={"year": 1, "month": 1},
)

I have several errors:  Missing/incomplete configuration file: /data/wp5/.cdsapirc, I attached the figures here.

Can you help me?

Thank you,
Cristina

![image](https://user-images.githubusercontent.com/56677048/223394570-355f7afe-38d1-4bdc-93d8-b4bc0427d252.png)
![image](https://user-images.githubusercontent.com/56677048/223395553-86617db5-bac7-478c-9e86-1029a97f84c4.png)

![image](https://user-images.githubusercontent.com/56677048/223394644-a7707eaa-d8fc-4381-87c9-71ffd470ad28.png)

**Comment by malmans2** [comment] 2023-03-07 10:49
Hi @Cri-dei,
Each WP should add a `.cdsapirc` which contains the credentials to access CDS data.
In your case, the file should go here: `/data/wp5/.cdsapirc`

If you are not familiar with `.cdsapirc`, check out this page: https://cds.climate.copernicus.eu/api-how-to

@vincenzodetoma wp5 is the only WP missing the cdsapirc, can you add yours?

**Comment by vincenzodetoma** [comment] 2023-03-07 10:54
Hi @malmans2, @Cri-dei, 
Ok I will try. However, in this way I will have to accept license agreement if necessary before accessing the data. I think I've already done this for ERA5, but in the future we'll have probably to find a better solution, for example defining url and keys for each user directly within the jupyter-notebook.

**Comment by vincenzodetoma** [comment] 2023-03-07 10:58
@Cri-dei Try now, it should work fine

**Comment by malmans2** [comment] 2023-03-07 11:02
If anyone needs to use their own cdsapirc, the can do this on top of their notebooks:
```python
import os
os.environ["CDSAPI_RC"] = os.path.expanduser("~/lastname_firstname/.cdsapirc"))
```
I will add it in the overview notebook.

**Comment by malmans2** [comment] 2023-03-08 10:01
These are connections issues with the VM and/or the CDS (see also: https://github.com/bopen/c3s-eqc-toolbox-template/issues/14).

Try to restart the kernel and re-run the notebook! Most of the files should be in the cache, so hopefully you'll be able to compute `ds_mean` very quickly.

**Comment by Cri-dei** [comment] 2023-03-10 14:41
Hi @malmans2 ,

I want to download satellite water level for lake Victoria. 
https://cds.climate.copernicus.eu/cdsapp#!/dataset/satellite-lake-water-level?tab=form
It is correct this code?

![image](https://user-images.githubusercontent.com/56677048/224344506-b39ba950-95b3-4e66-887d-5447c7182d00.png)


And then after that I wrote the request what is the command to just download the data? Without also doing the mean or other processing?

Thanks

**Comment by malmans2** [comment] 2023-03-10 14:48
Hi,
The `update_request_data` is only needed for datasets that are update very frequently.
In your case you dataset doesn't even have a time parameter.
```python
ds = download.download_and_transform(collection_id, request)
```

**Comment by Cri-dei** [comment] 2023-03-10 15:05
I attached the code, can you please look at it and leave me the comments?
I would like to download the entire data series, thanks.

![image](https://user-images.githubusercontent.com/56677048/224350249-cf7019bc-b147-4125-870f-97f8fd10612d.png)


[Lake water level(1).zip](https://github.com/bopen/c3s-eqc-toolbox-template/files/10943223/Lake.water.level.1.zip)

**Comment by malmans2** [comment] 2023-03-10 15:14
The parameter `variable` must be a string, whereas you are using python's builtin function `all`.
Try using this request:

```python
request = {
    "lake": "victoria",
    "variable": "all",
}
```

**Comment by Cri-dei** [comment] 2023-03-10 15:27
Okay now it works, but:

![image](https://user-images.githubusercontent.com/56677048/224355874-24786f92-b7b7-40ba-abb8-42ad9634453e.png)

**Comment by malmans2** [comment] 2023-03-10 15:30
You are hitting the issue @vincenzodetoma raised the other day.

> If anyone needs to use their own cdsapirc, they can do this on top of their notebooks:
> 
> ```python
> import os
> os.environ["CDSAPI_RC"] = os.path.expanduser("~/lastname_firstname/.cdsapirc")
> ```
> 
> I will add it in the overview notebook.

Either ask Vincenzo to accept the terms and conditions, or use your own cdsapirc as explained above.

**Comment by Cri-dei** [comment] 2023-03-13 14:45
Hi @malmans2 and @vincenzodetoma ,

I managed to fix the issue of cdsapirc, now is working. Actually now I am plotting a global map of lake water temperature dataset, but I have a memory error:

![image](https://user-images.githubusercontent.com/56677048/224736086-28ce8271-c286-42aa-95d6-67ac31ad3c86.png)


This is the request I did, but seems working:

![image](https://user-images.githubusercontent.com/56677048/224735300-d61f6ab0-3a0c-4630-961a-9bc60f178eb6.png)
![image](https://user-images.githubusercontent.com/56677048/224735377-5dca8309-aee0-424f-a59c-6198cc6ebb13.png)

**Comment by malmans2** [comment] 2023-03-13 14:53
Hi!

Can you please send me the whole code to reproduce the error please?
Also, it would be better to share the code rather than screenshots, so I can copy and paste.

If you wrap your code in three back quotes and you specify `python`, GH will automatically do syntax highlighting.
See: https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#syntax-highlighting

Thanks!

**Comment by malmans2** [comment] 2023-03-13 16:17
Hi @Cri-dei,

I see, there's a bug. I need to find a better workaround to handle satellites.
The problem is that in some cases we need to infer the time dimension from the filenames, and in other cases (like yours) we don't.
I'll let you know when it's fixed!

**Comment by malmans2** [comment] 2023-03-13 17:15
OK, should be fixed now.
I already updated the wp5 environment.

Try again and let me know. Keep in mind that the `source` dimension does not exist anymore for your dataset. That was a bug in your case, it's only needed for other datasets.

**Comment by Cri-dei** [comment] 2023-03-14 11:25
Hi @malmans2 ,

Now it is working thanks!
I need to install some packages:

**Comment by Cri-dei** [comment] 2023-03-14 11:27
Hi @malmans2 ,

Now is working thank you!

I need now to install some packages:

```       8 import pandas as pd
      9 import geopandas
---> 10 import rioxarray
     11 import xarray
     12 from shapely.geometry import mapping

ModuleNotFoundError: No module named 'rioxarray'```

These are that one that i need, don`t know that just rioxarray is not available or also some of the others.
Thanks

**Comment by Cri-dei** [comment] 2023-03-14 16:22
Works thanks!

It is taking very long time to download the data for all the available years.
It is not even showing the percentage bar.
Can I ask you if the request is correct?

Thank you so much.

[Lake water temperature (2).zip](https://github.com/bopen/c3s-eqc-toolbox-template/files/10971014/Lake.water.temperature.2.zip)

**Comment by malmans2** [comment] 2023-03-14 16:32
Probably the request is slow because it's quite big. You should chunk your requests.
For example, try:
```python
ds = download.download_and_transform(collection_id, request, chunks={"year": 1})
```

**Comment by Cri-dei** [comment] 2023-03-15 09:04
I am stucked. I reduced the number of years and I selected a smaller area but still I am not able to download the data.

```collection_id = "satellite-lake-water-temperature"
request = {
    'version': '4.0',
        'year': [
            #'1995', '1996', '1997',
            '1998', '1999', '2000',
            #'2001', '2002', '2003',
           # '2004', '2005', '2006',
            #'2007', '2008', '2009',
           # '2010', '2011', '2012',
            #'2013', '2014', '2015',
            #'2016', '2017', '2018',
            #'2019',
        ],
        'month': [
            '01', '02', '03',
           '12',
        ],
        'day': [
            '01', '02', '03',
            '04', '05', '06',
            '07', '08', '09',
            '10', '11', '12',
            '13', '14', '15',
            '16', '17', '18',
            '19', '20', '21',
            '22', '23', '24',
            '25', '26', '27',
            '28', '29', '30',
            '31',
        ],
        'variable': 'all',
        'area': [28, 41, -16,
            4,
        ]
    }

start = "2022-01"
stop = None```








``` requests = download.update_request_date(
    request, start=start, stop=stop)

ds = download.download_and_transform(collection_id, request, chunks={"year": 1})```



![Capture222](https://user-images.githubusercontent.com/56677048/225259803-51b2052d-fabd-4a58-be27-514e07239865.PNG)

**Comment by malmans2** [comment] 2023-03-15 09:26
I think you are experiencing this: https://github.com/bopen/c3s-eqc-toolbox-template/issues/14
B-Open does not maintain cdsapi nor the VM you are using, so unfortunately there's not much I can do about these connection errors.

Try to install the environment on your local machine and run locally.

**Comment by Cri-dei** [comment] 2023-03-15 09:35
If I use the function to directly download the monthly mean it can be more fast?
Can I ask you the command to directly download the monthly mean of the variable?

```
requests = download.update_request_date(
    request, start=start, stop=stop)

ds = download.download_and_transform(collection_id, request, chunks={"year": 1})
```

**Comment by malmans2** [comment] 2023-03-15 09:39
What is the collection_id of your dataset?

**Comment by Cri-dei** [comment] 2023-03-15 09:39
"satellite-lake-water-temperature"

**Comment by malmans2** [comment] 2023-03-15 09:42
This is the cds form:
https://cds.climate.copernicus.eu/cdsapp#!/dataset/satellite-lake-water-temperature?tab=form

There's no monthly option, so you can not download monthly data directly. If your chunks are big (I don't know the size of your dataset) you could try to chunk even more (month, day, ...).

**Comment by Cri-dei** [comment] 2023-03-15 09:52
Sorry I was not clear, I meant that I would like to use the package and directly download the transformed data in monthly mean. If in this command I want to transform directly the data in monthly mean:

```ds = download.download_and_transform(collection_id, request, chunks={"year": 1})```

I have to create a function? I saw in the documentation there is the spatial mean example.
```def spatial_daily_mean(ds: xr.Dataset) -> xr.Dataset:
    ds = diagnostics.spatial_weighted_mean(ds)
    return ds.resample(forecast_reference_time="1D").mean("forecast_reference_time")```


I would like to do just monthly mean.
Can I ask you the code for doing it?

Thank you so much.

**Comment by malmans2** [comment] 2023-03-15 10:00
I think you can just replace `"1D"` with `"1M"` and use the dimension name for your dataset.
But at the moment it looks like you are having problems downloading the data. The transform function is applied after downloading.

**Comment by Cri-dei** [comment] 2023-03-20 13:51
Hello, 
There have been some changes?
I am working today on the Jupyter Notebook again and I have errors from the starts with the packages and on the download command that till today was working without problems.

**Comment by malmans2** [comment] 2023-03-20 15:10
Hey @Cri-dei, I think I found the issue.
I had to pin xesmf on the VM environments.

Please try again and let me know if anything is broken.

I understand the frustration, but unfortunately the workflow on the VM is not ideal for developing, especially because at the moment all packages are in alpha stage. We are working with what we have, which is a VM with a single user.
We need to update often the environments so we are in sync with our changes and the changes upstream by ECMWF.

If you don't really need a shared cache (e.g., other people are not processing the same data you are using), you can always develop on your local machine. Then you can move to the VM once you are done developing and you need to run large computations.

**Comment by Cri-dei** [comment] 2023-03-20 16:22
Okay now it is working again. I need this package: import pymannkendall as mk.
Thanks.

**Comment by malmans2** [comment] 2023-03-20 17:56
Done!

**Comment by malmans2** [comment] 2023-03-21 11:29
Hi there,
If it's of use, there's a new notebook template under the satellite folder.

**Comment by Cri-dei** [comment] 2023-03-21 15:54
Hi @malmans2 ,

I attached here the final version of the code for two dataset: lakes water level, lakes surface water temperature and soil moisture.

For the code for the lakes surface water temperature I have some problems since I have a lot of warnings and it is not able to compute the trend.
The code for water level should be okay, that one for soil moisture can be optimized. I do the same plot for three different continents.

These are supposed to be the final code for the deadline of March, I still have to do other 2 dataset that I hope I can send you tomorrow.

Can you please start checking these one?
Thanks



![image](https://user-images.githubusercontent.com/56677048/226665425-cb79f385-7fd1-4984-890b-cf2522570abc.png)


[WG5_Jupyter Notebook.zip](https://github.com/bopen/c3s-eqc-toolbox-template/files/11030669/WG5_Jupyter.Notebook.zip)

**Comment by malmans2** [comment] 2023-03-21 16:07
OK, I'll take a look!
I've seen that error recently in a `xarray` issue, it looks like it's actually a bug in the latest netcdf-c.
We might have to pin `libnetcdf`, but I need to explore.

**Comment by Cri-dei** [comment] 2023-03-21 16:20
These are the file in jupyter notebook format, better you check this.
In the other comment was .py!

Thanks!

[0_Jupyter Notebook.zip](https://github.com/bopen/c3s-eqc-toolbox-template/files/11030941/0_Jupyter.Notebook.zip)

**Comment by malmans2** [comment] 2023-03-21 17:35
Hi @Cri-dei ,
I looked at the first one and added a template here: https://github.com/bopen/c3s-eqc-toolbox-template/tree/main/notebooks/wp5
I'll work on the other notebooks tomorrow.

**Comment by malmans2** [comment] 2023-03-22 08:52
Hi @Cri-dei,
Are the shapefiles that you are using in your notebook publicly available?
Could you please send me the link, so I can add a retrieve function and anyone can run the notebook?
Thanks.

**Comment by Cri-dei** [comment] 2023-03-22 09:32
Hi!
Yes it is in my folder in the VM, so I think it is public: Soil moisture/Continents.
http://localhost:5678/tree/Soil%20moisture/Continents
I attached the file also here.

[continent-poly.zip](https://github.com/bopen/c3s-eqc-toolbox-template/files/11038456/continent-poly.zip)

**Comment by Cri-dei** [comment] 2023-03-22 10:27
Hi @malmans2 ,

I am trying now to download the data of my last dataset: satellite-lai-fapar". But there are errors. I am doing something wrong in the request?
Thanks

```
collection_id = "satellite-lai-fapar"
request = {
'variable': [
            'fapar', 'lai',
        ],
        'satellite': 'proba',
        'sensor': 'vgt',
        'horizontal_resolution': '1km',
        'product_version': 'V2',
        'year': '2014',
        'month': [
            '01', '02', '03',
            '04', '05', '06',
            '07', '08', '09',
            '10', '11', '12',
        ],
        'nominal_day': [
            '03', '13', '21',
            '23', '24',
        ],
        'format': 'zip',
        'area': [90, -180, -90,
            180,
        ],
    }

start = "2022-01"
stop = None
```
 
![image](https://user-images.githubusercontent.com/56677048/226875270-03a8a335-3e98-476e-8346-386bcb4bb3fe.png)

**Comment by malmans2** [comment] 2023-03-22 14:11
> Hi @malmans2 ,
> 
> I am trying now to download the data of my last dataset: satellite-lai-fapar". But there are errors. I am doing something wrong in the request? Thanks
> 
> ```
> collection_id = "satellite-lai-fapar"
> request = {
> 'variable': [
>             'fapar', 'lai',
>         ],
>         'satellite': 'proba',
>         'sensor': 'vgt',
>         'horizontal_resolution': '1km',
>         'product_version': 'V2',
>         'year': '2014',
>         'month': [
>             '01', '02', '03',
>             '04', '05', '06',
>             '07', '08', '09',
>             '10', '11', '12',
>         ],
>         'nominal_day': [
>             '03', '13', '21',
>             '23', '24',
>         ],
>         'format': 'zip',
>         'area': [90, -180, -90,
>             180,
>         ],
>     }
> 
> start = "2022-01"
> stop = None
> ```
> 
> ![image](https://user-images.githubusercontent.com/56677048/226875270-03a8a335-3e98-476e-8346-386bcb4bb3fe.png)

I had a look at this, and even with the right permission looks like something's wrong. Probably that dataset needs some specific harmonisation function. I'll take a look either today or tomorrow.

**Comment by malmans2** [comment] 2023-03-22 14:54
The template on GH is not the final deliverable, it's just a guideline to help you making the final notebook. So yes, I would start from the templates of your use case, and edit what you need in order to finalise the deliverable (e.g., change years of interest, add markdown describing the data processing and results, ...).

If you need me to have another look at the very final version, I'm happy to do it.

Regarding the format of the deliverable (file name, contents, ...), you need to ask Chunxue.

(Because I'm actively working on your use case, please check often the templates. For example, I just made some minor changes to optimize caching even more).

**Comment by malmans2** [comment] 2023-03-22 18:55
Great!
Anything you keep in you dir is not going to mess with the `wp5` environment, so you can safely update.
For example, if you downloaded the template repo like this:
```
git clone https://github.com/bopen/c3s-eqc-toolbox-template.git
```
To update you have to do:
```
cd c3s-eqc-toolbox-template
git pull
```
But you don't have to edit the notebooks in `c3s-eqc-toolbox-template`, otherwise `git pull` is going to find conflicts.

**Comment by malmans2** [comment] 2023-03-22 19:01
I've uploaded the third notebook.

You can use a few functions we already developed for other evaluators: `utilis.regionalise`, `diagnostics.spatial_weighted_mean`, `plot.projected_map`.

In this notebook you should really start to see the benefit of caching. The original files are quite big, so we are caching the reduced spatial weighted means for each chunk.

Also, note that because this data is quite big, it's better to chunk months as well. Maybe this is why you were having troubles before.

Here is the notebook: https://github.com/bopen/c3s-eqc-toolbox-template/blob/main/notebooks/wp5/lake_water_temperature.ipynb

**Comment by malmans2** [comment] 2023-03-23 09:18
Hi @Cri-dei,

I'm done with the third notebook. Note that I've added a plotting function for your use case (and updated the env on the VM). If you want to take a look at the code, [here it is](https://github.com/bopen/c3s-eqc-automatic-quality-control/blob/388b65d32beab71fdbc0940aac00acd9c3a161e6/c3s_eqc_automatic_quality_control/plot.py#L405-L436).

I was going to debug `satellite-lai-fapar`, but it looks like the CDS is too busy at the moment and is taking too long to download. So I'm gonna look at the ERA5 land notebook.

**Comment by Cri-dei** [comment] 2023-03-23 09:49
Hi! 
Ya great :) For the Era5Land I was thinking that maybe we can use the same way of visualization of the trend for each continents, as we did for soil moisture with the new code you write. But Actually it seems there is no trend in temperature for Europe from my analysis, this is quite weird, so I focused on Spain and there I was able to catch the trend.

**Comment by Cri-dei** [comment] 2023-03-23 12:26
Hi,
Unfortunaltely I don't have time to change it now, so I would like to leave it as it is.
Can you please tell me when the satellite-lai-fapar is working? Thanks!

**Comment by malmans2** [comment] 2023-03-23 12:52
The request you've been doing was huge! I think that was causing the issue.
I ran a small test with these parameters, and it worked fine:
```python
ds = download.download_and_transform(
    collection_id,
    request,
    chunks={"month": 1, "nominal_day": 1},
    data_vars='minimal',
    coords='minimal',
    compat='override'
    )
```
I'm now running the entire request you had in your comment on WP5, let's see how it goes.
If it works fine, you'll have it ready and cached on the VM.

**Comment by malmans2** [comment] 2023-03-23 16:05
The queue for `satellite-lai-fapar` is too long at the moment, I can't debug from the screenshot  because it's missing the some of the traceback and the code. I'll get it done either tomorrow or early next week.

**Comment by malmans2** [comment] 2023-03-23 16:08
The ERA5 notebook is ready. You can use most of the functions already implemented, but I had to fix something in `c3s_eqc_automatic_quality_control` to deal with the time coordinates of ERA5.

Here is how it looks the notebook executed: 
[for-cristina.zip](https://github.com/bopen/c3s-eqc-toolbox-template/files/11053080/for-cristina.zip)

In order for you to be able to run it, I'll have to update the environment on the VM. I also need to wipe the cache, as today I implemented a few improvements. Please let me know when I can go ahead and do the update.

**Comment by malmans2** [comment] 2023-03-24 15:31
Hi @Cri-dei,
The `satellite-lai-fapar` is a tricky one. The spatial dimensions are `40320 x 15680`, I quickly run out of memory on the VM whenever I try to do anything. How do you usually process it? Do you use some large memory cluster?

Are you going to need the whole globe or are you going to focus on a specific area like the other notebooks? If the latter, we should really download and cache specific areas only. Also, are you actually going to need all nominal_days or that was just a test?

**Comment by malmans2** [comment] 2023-03-24 15:57
Actually, I'm not really sure why, but I think I found the issue.
Somehow there's something about the 2 variables requested that causes problems. I'm able to do some basic stats of both of them if I handle them separately. So at least until we figure out exactly what's happening, you'll have to work with 2 separate datasets.

Please send me the minimum request you need to start your analysis. So basically, let me know if you actually need the whole request you shared before, or we can cut it down to a smaller dataset. I will test the request you send me, populate the cache, and if everything works fine I'll send you the code to open the datasets.

**Comment by Cri-dei** [comment] 2023-03-27 10:37
Hi @malmans2 ,

My idea is to do exactly the same analysis I did for soil moisture for a subset of Fapar data, so to show the data availability for a specific time period. So the code will be the same of soil moisture but as in input the fapar Lai data.
I think we can do it just with one of the two variables and select just a subset. Maybe, Europe? or South America?
And we calculate the percentage of missing value for that area.
So for me I need not world extend but just Europe or another continent it is okay!

**Comment by Cri-dei** [comment] 2023-03-27 13:16
This is the request, but it is just for one year (2014), if it is possible to extract the mean of the month directly it is also okay.

''' collection_id = "satellite-lai-fapar"
request = {
'variable': [
            'fapar', 'lai',
        ],
        'satellite': 'proba',
        'sensor': 'vgt',
        'horizontal_resolution': '1km',
        'product_version': 'V2',
        'year': '2014',
        'month': [
            '01', '02', '03',
            '04', '05', '06',
            '07', '08', '09',
            '10', '11', '12',
        ],
        'nominal_day': [
            '03', '13', '21',
            '23', '24',
        ],
        'format': 'zip',
        'area': [ 72, -13, 40,
                35,
        ],
    }

start = "2022-01"
stop = None '''

**Comment by malmans2** [comment] 2023-03-28 21:12
@Cri-dei good news,
I just checked a script I've been running during the meeting and looks like you can now work with `"satellite-lai-fapar"` (and you can have both fapar and lai in the same dataset).
Here is the code:
```python
from c3s_eqc_automatic_quality_control import download, utils

# Request parameters
year_start = 2014
year_stop = 2014
nominal_days = [3, 13, 21, 23, 24]
variables = ["fapar", "lai"]

# Region
lon_slice = slice(-13, 35)
lat_slice = slice(72, 40)

# Define request
collection_id = "satellite-lai-fapar"
request = {
    "satellite": "proba",
    "sensor": "vgt",
    "horizontal_resolution": "1km",
    "product_version": "V2",
    "year": [str(year) for year in range(year_start, year_stop + 1)],
    "month": [f"{month:02d}" for month in range(1, 12 + 1)],
    "nominal_day": [f"{day:02d}" for day in nominal_days],
    "format": "zip",
    "variable": variables,
}

# Download and cache
ds = download.download_and_transform(
    collection_id,
    request,
    transform_func=utils.regionalise,
    transform_func_kwargs={
        "lon_slice": lon_slice,
        "lat_slice": lat_slice,
    },
    chunks={"year": 1, "nominal_day": 1, "variable": 1},
    combine="nested",
    concat_dim="time",
)
```
The code above is cached on the VM, so if you use it as it is, you should get the dataset in just a few seconds.

I'm closing this issue, but feel free to open a new one if you experience any problems or you have questions.
See you tomorrow!

PS: In the future, please try to avoid mixing topics or notebooks in the same issue. There are also new issue templates to help with that.

**Closed by malmans2** 2023-03-28 21:12 UTC
Labels: wp5, notebook
