### ISSUE TITLE
Can't run properly the ERA5 Template

### ISSUE THREAD

**Issue by vincenzodetoma** [bopen/c3s-eqc-toolbox-template#6] opened 2022-12-23 12:02 UTC
Hi, I'm trying to run the ERA5 Application template notebook, but when I run the following cell
```
daily_global_t2m = download.download_and_transform(
    collection_id,
    requests,
    chunks=chunks,
    func=spatial_daily_mean,
    open_with="xarray",
)

daily_global_t2m
```
I get the following errors:
```
INFO     Gathering file 1 out of 18...                                                                             
OperationalError                          Traceback (most recent call last)
File /data/eqcuser/software/miniconda3/envs/c3s/lib/python3.10/site-packages/sqlalchemy/engine/base.py:1900, in Connection._execute_context(self, dialect, constructor, statement, parameters, execution_options, *args, **kw)
   1899     if not evt_handled:
-> 1900         self.dialect.do_execute(
   1901             cursor, statement, parameters, context
   1902         )
   1904 if self._has_events or self.engine._has_events:

File /data/eqcuser/software/miniconda3/envs/c3s/lib/python3.10/site-packages/sqlalchemy/engine/default.py:736, in DefaultDialect.do_execute(self, cursor, statement, parameters, context)
    735 def do_execute(self, cursor, statement, parameters, context=None):
--> 736     cursor.execute(statement, parameters)

OperationalError: attempt to write a readonly database

The above exception was the direct cause of the following exception:

OperationalError                          Traceback (most recent call last)
File /data/eqcuser/software/miniconda3/envs/c3s/lib/python3.10/site-packages/cacholote/cache.py:169, in cacheable.<locals>.wrapper(__context__, *args, **kwargs)
    168     session.add(cache_entry)
--> 169     session.commit()
    170 except sqlalchemy.exc.IntegrityError:
    171     # Concurrent job: This cache entry already exists.

File /data/eqcuser/software/miniconda3/envs/c3s/lib/python3.10/site-packages/sqlalchemy/orm/session.py:1451, in Session.commit(self)
   1449         raise sa_exc.InvalidRequestError("No transaction is begun.")
-> 1451 self._transaction.commit(_to_root=self.future)

File /data/eqcuser/software/miniconda3/envs/c3s/lib/python3.10/site-packages/sqlalchemy/orm/session.py:829, in SessionTransaction.commit(self, _to_root)
    828 if self._state is not PREPARED:
--> 829     self._prepare_impl()
    831 if self._parent is None or self.nested:

File /data/eqcuser/software/miniconda3/envs/c3s/lib/python3.10/site-packages/sqlalchemy/orm/session.py:808, in SessionTransaction._prepare_impl(self)
    807         break
--> 808     self.session.flush()
    809 else:

File /data/eqcuser/software/miniconda3/envs/c3s/lib/python3.10/site-packages/sqlalchemy/orm/session.py:3444, in Session.flush(self, objects)
   3443     self._flushing = True
-> 3444     self._flush(objects)
   3445 finally:

File /data/eqcuser/software/miniconda3/envs/c3s/lib/python3.10/site-packages/sqlalchemy/orm/session.py:3583, in Session._flush(self, objects)
   3582 except:
-> 3583     with util.safe_reraise():
   3584         transaction.rollback(_capture_exception=True)

File /data/eqcuser/software/miniconda3/envs/c3s/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py:70, in safe_reraise.__exit__(self, type_, value, traceback)
     69     if not self.warn_only:
---> 70         compat.raise_(
     71             exc_value,
     72             with_traceback=exc_tb,
     73         )
     74 else:

File /data/eqcuser/software/miniconda3/envs/c3s/lib/python3.10/site-packages/sqlalchemy/util/compat.py:211, in raise_(***failed resolving arguments***)
    210 try:
--> 211     raise exception
    212 finally:
    213     # credit to
    214     # https://cosmicpercolator.com/2016/01/13/exception-leaks-in-python-2-and-3/
    215     # as the __traceback__ object creates a cycle

File /data/eqcuser/software/miniconda3/envs/c3s/lib/python3.10/site-packages/sqlalchemy/orm/session.py:3544, in Session._flush(self, objects)
   3543 try:
-> 3544     flush_context.execute()
   3545 finally:

File /data/eqcuser/software/miniconda3/envs/c3s/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py:456, in UOWTransaction.execute(self)
    455 for rec in topological.sort(self.dependencies, postsort_actions):
--> 456     rec.execute(self)

File /data/eqcuser/software/miniconda3/envs/c3s/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py:630, in SaveUpdateAll.execute(self, uow)
    628 @util.preload_module("sqlalchemy.orm.persistence")
    629 def execute(self, uow):
--> 630     util.preloaded.orm_persistence.save_obj(
    631         self.mapper,
    632         uow.states_for_mapper_hierarchy(self.mapper, False, False),
    633         uow,
    634     )

File /data/eqcuser/software/miniconda3/envs/c3s/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py:245, in save_obj(base_mapper, states, uowtransaction, single)
    237     _emit_update_statements(
    238         base_mapper,
    239         uowtransaction,
   (...)
    242         update,
    243     )
--> 245     _emit_insert_statements(
    246         base_mapper,
    247         uowtransaction,
    248         mapper,
    249         table,
    250         insert,
    251     )
    253 _finalize_insert_update_commands(
    254     base_mapper,
    255     uowtransaction,
   (...)
    271     ),
    272 )

File /data/eqcuser/software/miniconda3/envs/c3s/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py:1097, in _emit_insert_statements(base_mapper, uowtransaction, mapper, table, insert, bookkeeping)
   1095 multiparams = [rec[2] for rec in records]
-> 1097 c = connection._execute_20(
   1098     statement, multiparams, execution_options=execution_options
   1099 )
   1101 if bookkeeping:

File /data/eqcuser/software/miniconda3/envs/c3s/lib/python3.10/site-packages/sqlalchemy/engine/base.py:1705, in Connection._execute_20(self, statement, parameters, execution_options)
   1704 else:
-> 1705     return meth(self, args_10style, kwargs_10style, execution_options)

File /data/eqcuser/software/miniconda3/envs/c3s/lib/python3.10/site-packages/sqlalchemy/sql/elements.py:334, in ClauseElement._execute_on_connection(self, connection, multiparams, params, execution_options, _force)
    333 if _force or self.supports_execution:
--> 334     return connection._execute_clauseelement(
    335         self, multiparams, params, execution_options
    336     )
    337 else:

File /data/eqcuser/software/miniconda3/envs/c3s/lib/python3.10/site-packages/sqlalchemy/engine/base.py:1572, in Connection._execute_clauseelement(self, elem, multiparams, params, execution_options)
   1564 compiled_sql, extracted_params, cache_hit = elem._compile_w_cache(
   1565     dialect=dialect,
   1566     compiled_cache=compiled_cache,
   (...)
   1570     linting=self.dialect.compiler_linting | compiler.WARN_LINTING,
   1571 )
-> 1572 ret = self._execute_context(
   1573     dialect,
   1574     dialect.execution_ctx_cls._init_compiled,
   1575     compiled_sql,
   1576     distilled_params,
   1577     execution_options,
   1578     compiled_sql,
   1579     distilled_params,
   1580     elem,
   1581     extracted_params,
   1582     cache_hit=cache_hit,
   1583 )
   1584 if has_events:

File /data/eqcuser/software/miniconda3/envs/c3s/lib/python3.10/site-packages/sqlalchemy/engine/base.py:1943, in Connection._execute_context(self, dialect, constructor, statement, parameters, execution_options, *args, **kw)
   1942 except BaseException as e:
-> 1943     self._handle_dbapi_exception(
   1944         e, statement, parameters, cursor, context
   1945     )
   1947 return result

File /data/eqcuser/software/miniconda3/envs/c3s/lib/python3.10/site-packages/sqlalchemy/engine/base.py:2124, in Connection._handle_dbapi_exception(self, e, statement, parameters, cursor, context)
   2123 elif should_wrap:
-> 2124     util.raise_(
   2125         sqlalchemy_exception, with_traceback=exc_info[2], from_=e
   2126     )
   2127 else:

File /data/eqcuser/software/miniconda3/envs/c3s/lib/python3.10/site-packages/sqlalchemy/util/compat.py:211, in raise_(***failed resolving arguments***)
    210 try:
--> 211     raise exception
    212 finally:
    213     # credit to
    214     # https://cosmicpercolator.com/2016/01/13/exception-leaks-in-python-2-and-3/
    215     # as the __traceback__ object creates a cycle

File /data/eqcuser/software/miniconda3/envs/c3s/lib/python3.10/site-packages/sqlalchemy/engine/base.py:1900, in Connection._execute_context(self, dialect, constructor, statement, parameters, execution_options, *args, **kw)
   1899     if not evt_handled:
-> 1900         self.dialect.do_execute(
   1901             cursor, statement, parameters, context
   1902         )
   1904 if self._has_events or self.engine._has_events:

File /data/eqcuser/software/miniconda3/envs/c3s/lib/python3.10/site-packages/sqlalchemy/engine/default.py:736, in DefaultDialect.do_execute(self, cursor, statement, parameters, context)
    735 def do_execute(self, cursor, statement, parameters, context=None):
--> 736     cursor.execute(statement, parameters)

OperationalError: (sqlite3.OperationalError) attempt to write a readonly database
[SQL: INSERT INTO cache_entries ("key", expiration, result, timestamp, counter, tag) VALUES (?, ?, ?, ?, ?, ?)]
[parameters: ('8915418fb7f2ab47b8fbbd0003a91c6ce310d2e4ce114546b714567b', '9999-12-31 23:59:59.999999', '"__locked__"', '2022-12-23 11:51:06.106564', 0, None)]
(Background on this error at: https://sqlalche.me/e/14/e3q8)

During handling of the above exception, another exception occurred:

InvalidRequestError                       Traceback (most recent call last)
Cell In [7], line 1
----> 1 daily_global_t2m = download.download_and_transform(
      2     collection_id,
      3     requests,
      4     chunks=chunks,
      5     func=spatial_daily_mean,
      6     open_with="xarray",
      7 )
      9 daily_global_t2m

File /data/eqcuser/software/c3s-eqc-automatic-quality-control/c3s_eqc_automatic_quality_control/download.py:349, in download_and_transform(collection_id, requests, chunks, split_all, func, open_with, logger, **kwargs)
    347 for n, request_chunk in enumerate(request_list):
    348     logger.info(f"Gathering file {n+1} out of {len(request_list)}...")
--> 349     ds = download_and_transform_chunk(
    350         collection_id, request=request_chunk, func=func, open_with=open_with
    351     )
    352     datasets.append(ds)
    353 logger.info("Aggregating data...")

File /data/eqcuser/software/miniconda3/envs/c3s/lib/python3.10/site-packages/cacholote/cache.py:195, in cacheable.<locals>.wrapper(__context__, *args, **kwargs)
    192 finally:
    193     # Unlock
    194     if cache_entry and cache_entry.result == _LOCKER:
--> 195         _delete_cache_entry(session, cache_entry)

File /data/eqcuser/software/miniconda3/envs/c3s/lib/python3.10/site-packages/cacholote/cache.py:71, in _delete_cache_entry(session, cache_entry)
     68 def _delete_cache_entry(
     69     session: sqlalchemy.orm.Session, cache_entry: config.CacheEntry
     70 ) -> None:
---> 71     session.delete(cache_entry)
     72     session.commit()
     73     # Delete cache file

File /data/eqcuser/software/miniconda3/envs/c3s/lib/python3.10/site-packages/sqlalchemy/orm/session.py:2707, in Session.delete(self, instance)
   2701 except exc.NO_STATE as err:
   2702     util.raise_(
   2703         exc.UnmappedInstanceError(instance),
   2704         replace_context=err,
   2705     )
-> 2707 self._delete_impl(state, instance, head=True)

File /data/eqcuser/software/miniconda3/envs/c3s/lib/python3.10/site-packages/sqlalchemy/orm/session.py:2713, in Session._delete_impl(self, state, obj, head)
   2711 if state.key is None:
   2712     if head:
-> 2713         raise sa_exc.InvalidRequestError(
   2714             "Instance '%s' is not persisted" % state_str(state)
   2715         )
   2716     else:
   2717         return

InvalidRequestError: Instance '<CacheEntry at 0x7f788ca1b0d0>' is not persisted
```

What can I do to solve the problem? I cannot figure out what the problem is. I successfully Installed both the toolbox template package and also the automatic quality check package. 
(PS: In your notebook the link to it is wrong, it should be not https://github.com/bopen/c3s_eqc_automatic_quality_control, but 
https://github.com/bopen/c3s-eqc-automatic-quality-control, please change it when you can.)

**Comment by vincenzodetoma** [comment] 2022-12-23 13:16
I pulled again all the necessary repositories and made another try, Now the error is changed to:
```

INFO     Gathering file 1 out of 18...                                                                             
                                                   
units
WARNING  Error while translating coordinate: valid_time.                                                           
          Traceback:                                                                                               
         the new name 'time' conflicts                                                                             
INFO     Gathering file 2 out of 18...                                                                             
                                                   
units
WARNING  Error while translating coordinate: valid_time.                                                           
          Traceback:                                                                                               
         the new name 'time' conflicts                                                                             
INFO     Gathering file 3 out of 18...                                                                             
                                                   
units
WARNING  Error while translating coordinate: valid_time.                                                           
          Traceback:                                                                                               
         the new name 'time' conflicts                                                                             
INFO     Gathering file 4 out of 18...                                                                             
                                                   
units
WARNING  Error while translating coordinate: valid_time.                                                           
          Traceback:                                                                                               
         the new name 'time' conflicts                                                                             
INFO     Gathering file 5 out of 18...                                                                             
                                                   
units
WARNING  Error while translating coordinate: valid_time.                                                           
          Traceback:                                                                                               
         the new name 'time' conflicts                                                                             
INFO     Gathering file 6 out of 18...                                                                             
                                                   
units
WARNING  Error while translating coordinate: valid_time.                                                           
          Traceback:                                                                                               
         the new name 'time' conflicts                                                                             
INFO     Gathering file 7 out of 18...                                                                             
                                                   
units
WARNING  Error while translating coordinate: valid_time.                                                           
          Traceback:                                                                                               
         the new name 'time' conflicts                                                                             
INFO     Gathering file 8 out of 18...                                                                             
                                                   
units
WARNING  Error while translating coordinate: valid_time.                                                           
          Traceback:                                                                                               
         the new name 'time' conflicts                                                                             
INFO     Gathering file 9 out of 18...                                                                             
                                                   
units
WARNING  Error while translating coordinate: valid_time.                                                           
          Traceback:                                                                                               
         the new name 'time' conflicts                                                                             
INFO     Gathering file 10 out of 18...                                                                            
                                                   
units
WARNING  Error while translating coordinate: valid_time.                                                           
          Traceback:                                                                                               
         the new name 'time' conflicts                                                                             
INFO     Gathering file 11 out of 18...                                                                            
                                                   
units
WARNING  Error while translating coordinate: valid_time.                                                           
          Traceback:                                                                                               
         the new name 'time' conflicts                                                                             
INFO     Gathering file 12 out of 18...                                                                            
                                                   
units
WARNING  Error while translating coordinate: valid_time.                                                           
          Traceback:                                                                                               
         the new name 'time' conflicts                                                                             
INFO     Gathering file 13 out of 18...                                                                            
                                                   
units
WARNING  Error while translating coordinate: valid_time.                                                           
          Traceback:                                                                                               
         the new name 'time' conflicts                                                                             
INFO     Gathering file 14 out of 18...                                                                            
                                                   
units
WARNING  Error while translating coordinate: valid_time.                                                           
          Traceback:                                                                                               
         the new name 'time' conflicts                                                                             
INFO     Gathering file 15 out of 18...                                                                            
                                                   
units
WARNING  Error while translating coordinate: valid_time.                                                           
          Traceback:                                                                                               
         the new name 'time' conflicts                                                                             
INFO     Gathering file 16 out of 18...                                                                            
                                                   
units
WARNING  Error while translating coordinate: valid_time.                                                           
          Traceback:                                                                                               
         the new name 'time' conflicts                                                                             
INFO     Gathering file 17 out of 18...                                                                            
                                                   
units
WARNING  Error while translating coordinate: valid_time.                                                           
          Traceback:                                                                                               
         the new name 'time' conflicts                                                                             
INFO     Gathering file 18 out of 18...                                                                            
                                                   
units
WARNING  Error while translating coordinate: valid_time.                                                           
          Traceback:                                                                                               
         the new name 'time' conflicts                                                                             
INFO     Aggregating data...                                                                                       
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In [7], line 1
----> 1 daily_global_t2m = download.download_and_transform(
      2     collection_id,
      3     requests,
      4     chunks=chunks,
      5     func=spatial_daily_mean,
      6     open_with="xarray",
      7 )
      9 daily_global_t2m

File /data/eqcuser/software/c3s-eqc-automatic-quality-control/c3s_eqc_automatic_quality_control/download.py:357, in download_and_transform(collection_id, requests, chunks, split_all, transform_func, open_with, logger, **kwargs)
    355 if open_with == "xarray":
    356     with dask.config.set({"array.slicing.split_large_chunks": True}):
--> 357         ds = xr.merge(datasets, **kwargs)
    358 else:
    359     ds = pd.concat(datasets, **kwargs)

TypeError: merge() got an unexpected keyword argument 'func'

```

**Comment by malmans2** [comment] 2022-12-23 14:33
Hi @vincenzodetoma,

Giuseppe and I are actively working on it. You are experiencing problems because we are changing various libraries used by the notebooks. Please hold on, I'll let you know when we are done and you'll be able to try out the new templates.
We should be able to also upload an example for all datasets by the end of today.

**Comment by vincenzodetoma** [comment] 2022-12-23 15:51
Ok thanks, @malmans2, 
In the meanwhile, I found a workaround, which is to load the request into a xarray object without passing any func argument and applying the function later, but this makes it possible to use just a little piece of data (I tried on three years of monthly data of latent heat flux from ERA5). 
In case, I'll modify later my work based on the solution you'll find!! 
Thanks :)

**Comment by malmans2** [comment] 2022-12-23 16:07
The traceback shows that you are not using the latest `c3s-eqc-automatic-quality-control`, so the problem is mainly that the notebooks and the aqc code are not in sync.
If you look at the PR open in this repo you'll see that all new notebooks (A-, B-, ...) are in sync with aqc (there's a PR in the aqc repo as well though).

We are working on it right now, so don't expect it to be stable.

The goal is to have everything in good shape by the end of the month. We will also make a release of all packages once we are done (many packages are affected: template, aqc, cache, harmonizer, and file opener).

**Comment by malmans2** [comment] 2022-12-23 18:23
Hi @vincenzodetoma ,
You should be able to update the environment and run all notebooks.
A few things changed and you'll notice that we are not supporting pandas at the moment.
Reanalysis (single/pressure levels), and in situ (gridded/ungridded) notebooks are now available.
We'll add more templates and markdowns in the notebooks next week.

Buone Feste!

**Comment by vincenzodetoma** [comment] 2022-12-23 18:29
Thanks a lot @malmans2, 
I will take a look!! Shall we keep open this issue, so if I ecounter other problems I write directly here? 
Buone Feste!!

**Comment by malmans2** [comment] 2022-12-23 18:33
Sounds good!
I'll be working next week, feel free to write here if you find any issues.

**Comment by malmans2** [comment] 2023-01-19 11:54
Hi, 
I'm going to close this just because it's easier to keep track of issues.
Feel free to re-open or open more issues in the future!

**Closed by malmans2** 2023-01-19 11:54 UTC
