### ISSUE TITLE
OSError when downloading Copernicus Land Use Land Cover data

### ISSUE THREAD

**Issue by Figas23** [bopen/c3s-eqc-toolbox-template#51] opened 2023-05-04 15:38 UTC
### What happened?

I am trying to download Copernicus Land Cover data using the following code:

```python
from c3s_eqc_automatic_quality_control import download, utils

year_start = 2020
year_stop = 2020

####Select Region of interest (ROI)
lon_slice = slice(-10, 2)
lat_slice = slice(45, 35)

#####Download and transform (cached)
request = (
    "satellite-land-cover",
    {
        "variable": "all",
        "format": "zip",
        "version": "v2.1.1",
        "year": [str(year) for year in range(year_start, year_stop + 1)],
    },
)
ds = download.download_and_transform(
    *request,
    chunks={"year": 1},
    transform_func=utils.regionalise,
    transform_func_kwargs={"lon_slice": lon_slice, "lat_slice": lat_slice},
)

####Rename time dimension
ds["time"] = ds["time"].dt.year
ds = ds.rename(time="year")
```

However, I am getting an OSError with the following error message:

```
OSError: [Errno -101] NetCDF: HDF error: '/tmp/cacholote/cache_files/8068a489bc13204d92c0614319f3828e/C3S-LC-L4-LCCS-Map-300m-P1Y-2020-v2.1.1.nc'
```

I am not sure why this error is occurring. Can someone please help me troubleshoot this issue? Thank you in advance for your help.
Please let me know if you have any questions or need any additional information. Thank you.

### Environment

<details>

</details>

**Comment by Figas23** [comment] 2023-05-04 15:45
Hey @malmans2 
No i am running in my machine

**Comment by malmans2** [comment] 2023-05-04 16:16
Hi @Figas23,
Looks like the original data is corrupted.
I've downloaded the data directly from the CDS, unzipped, and tried `ncdump -h` on the netcdf file and I get the same error.

Unfortunately, I think you have to get in touch with ECMWF and report the issue.

In case you need it, this is the request I used to download the raw data using `cdsapi`:
```python
import cdsapi

c = cdsapi.Client()

c.retrieve(
    'satellite-land-cover',
    {
        'year': '2020',
        'version': 'v2.1.1',
        'variable': 'all',
        'format': 'zip',
    },
    'download.zip')
```

**Comment by Figas23** [comment] 2023-05-04 16:25
Ok @malmans2 

Thank you for your help. I will get in touch with ECMWF.

**Comment by malmans2** [comment] 2023-05-04 16:28
I'm closing this as it's not related to our software.
Could you please keep me updated though? You should be able to add comments even if the issue is closed.
Thanks!

**Closed** 2023-05-04 16:28 UTC
Labels: bug
