### ISSUE TITLE
satellite sea ice thickness

### ISSUE THREAD

**Issue by tdcwilliams** [bopen/c3s-eqc-toolbox-template#127] opened 2024-01-22 12:42 UTC
### Notebook description

For each month and the variable sea ice thickness, I want to calculate the mean, standard deviation, trend and some goodness of fit parameter eg r^2 or p-value.

I would eventually like to plot maps of these statistics.

### Notebook link or upload

[sat_sithick.ipynb.zip](https://github.com/bopen/c3s-eqc-toolbox-template/files/14010178/sat_sithick.ipynb.zip)

### Anything else we need to know?

wp4.

You can see the error when `diagnostics.time_weighted_linear_trend` is called with `p_value=True`.
It works when `p_value=False`

### Environment

wp4 environment

**Comment by malmans2** [comment] 2024-01-29 10:51
Hi @tdcwilliams,

Sorry about the delay. The issue is that for this kind of operations we can not have chunked data along the time dimension.
It should be fixed now.

- Here is the template: https://github.com/bopen/c3s-eqc-toolbox-template/blob/main/notebooks/wp4/satellite_sea_ice_thickness.ipynb
- Here is the notebook executed: https://gist.github.com/malmans2/78bb19d1b3c3a717718c31946186824b

I also added maps for each variable.
Let me know if it works OK.

Mattia

**Comment by malmans2** [comment] 2024-01-30 08:23
Hi @tdcwilliams,

Does this notebook replaces #103?

**Comment by tdcwilliams** [comment] 2024-01-30 08:41
Hi @malmans2, thanks a lot for fixing this. I'll take a look tomorrow since I'm a bit sick today. But it wasn't intended to replace #103 which was to evaluate CMIP6 thickness.

**Comment by tdcwilliams** [comment] 2024-01-31 13:06
Hi @malmans2, thanks - that runs for me. I was wondering if you could implement an r-squared value as another metric for how appropriate the linear trend is?

**Comment by malmans2** [comment] 2024-02-01 15:10
Hi @tdcwilliams,

I've added r2. Here is the [latest notebook](https://gist.github.com/malmans2/78bb19d1b3c3a717718c31946186824b).
Let me know if it looks OK.

**Comment by malmans2** [comment] 2024-02-02 16:04
Hi @tdcwilliams,

Today I noticed that you've been accessing wp5 recently.
I always cached your data on wp4.
It's not a big deal, but if you are running your notebooks on wp5 we are duplicating data.

(I usually put a tag on the issue with the WP where I'm running the template)

**Comment by tdcwilliams** [comment] 2024-02-05 13:14
Hi @malmans2,
I'm now working on the satellite sea ice tasks in wp5, which is why I am over there.
Thanks for adding the r2 statistic - the notebook should be fine now.

**Comment by malmans2** [comment] 2024-02-05 13:35
OK, should I move this notebook to the wp5?
https://github.com/bopen/c3s-eqc-toolbox-template/blob/main/notebooks/wp4/satellite_sea_ice_thickness.ipynb

**Comment by tdcwilliams** [comment] 2024-02-05 13:43
yes please

**Comment by malmans2** [comment] 2024-02-05 13:46
Done!

**Closed by malmans2** 2024-02-05 13:46 UTC
Labels: wp5, notebook

**Comment by tdcwilliams** [comment] 2024-02-05 14:25
thanks @malmans2
