### ISSUE TITLE
Submission of my code (make_C3S_uvgeo_diagnostics.zip)

### ISSUE THREAD

**Issue by evanmason** [bopen/c3s-eqc-toolbox-template#37] opened 2023-04-05 08:19 UTC
Hi @malmans2 
Did you receive my Python file that I submitted yesterday? I am aware that the code is quite extensive. I would like to convert it into a notebook, but I still don't quite know how to do that.
Thanks, Evan

**Comment by malmans2** [comment] 2023-04-18 11:17
Looks like a duplicate of #42, but feel free to re-open this if that's not the case.

**Closed by malmans2** 2023-04-18 11:17 UTC
Labels: question
