### ISSUE TITLE
Downoad warning

### ISSUE THREAD

**Issue by paololanteri** [bopen/c3s-eqc-toolbox-template#14] opened 2023-01-19 10:57 UTC
The download of climate projection data is usually successfull at the beginning but fail after the dowload of about 4/5 files (chunked annually). I get the following warning:
```
WARNING  Recovering from connection error [HTTPSConnectionPool(host='download-0008-clone.copernicus-climate.eu',   
         port=443): Max retries exceeded with url:                                                                 
         /cache-compute-0008/cache/data2/adaptor.esgf_wps.retrieve-1674125120.2645676-9527-16-c2c2698c-8a04-48e7-94
         90-7d28a7b3dcb6.zip (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at          
         0x7f8cd2e9a0b0>, 'Connection to download-0008-clone.copernicus-climate.eu timed out. (connect             
         timeout=60)'))], attemps 0 of 500
```

Here the request that failed (just as an example):

```
collection_id = "projections-cmip6"
year_start = 1985
year_stop = 2014
request = {
    "format": "zip",
    "temporal_resolution": "monthly",
    "experiment": "historical",
    "variable": "near_surface_air_temperature",
    "model": "cmcc_cm2_sr5",
    "year": [str(year) for year in range(year_start, year_stop + 1)],
    "month": [f"{month:02d}" for month in range(1, 12 + 1)],
}

ds = download.download_and_transform(
    collection_id,
    request,
    transform_func=drop_bounds_and_spatial_weighted_mean, #drop_bounds_and_time_mean
    #split_all=True,
    chunks={"year": 1},
)
```

**Comment by malmans2** [comment] 2023-01-19 11:51
Hi @paololanteri, this looks like a connection problem triggered by `cdsapi`. 
Can you try to download smaller chunks?
For example, what happen if you use `{"year": 1, "month": 6}` or even smaller?

**Comment by paololanteri** [comment] 2023-01-19 14:38
Thank you Mattia,
The problem of making many small chunks is that being climate projections very long in time, making too many cdsapi requests make the process very slow. 

Anyway, I tried with {"year": 1, "month": 3} and the problem still remain.
I also tried to run a normal cdsapi request on the VM with a for cycle (one request per year), and it stops in the same way.

However, when I run the same normal cdsapi request on my laptop everything works fine!

**Comment by paololanteri** [comment] 2023-01-20 08:52
Ok, I tried also with ERA5 and I got the same warning. 
I will try to report this problem, 
thank you!

**Comment by EddyCMWF** [comment] 2023-03-17 09:29
Hi @malmans2 , is this issue resolved with version 0.6.1 of the cdsapi?

**Comment by malmans2** [comment] 2023-03-17 10:09
So far so good, although I didn't run many requests yet.

All VM environments now use the latest cdsapi, and all users have been notified.
@paololanteri could you please try again to work on the VM and let us know how it goes?

**Comment by paololanteri** [comment] 2023-03-17 10:14
Hi
Yes I confirm that in the last weeks we (WP4) worked on our local machines, so I have no update right now, but I will let you know as soon as possible (this afternoon I hope).

**Comment by paololanteri** [comment] 2023-03-17 17:49
Great news, it seems to work correctly.

**Comment by malmans2** [comment] 2023-03-21 15:14
I'm closing this as it looks like the issue is fixed.
Feel free to reopen though!

**Closed by malmans2** 2023-03-21 15:14 UTC
